/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UstozRouteImport } from './routes/ustoz'
import { Route as NatijalarRouteImport } from './routes/natijalar'
import { Route as KurslarRouteImport } from './routes/kurslar'
import { Route as ImmigratsiyaRouteImport } from './routes/immigratsiya'
import { Route as GalereyaRouteImport } from './routes/galereya'
import { Route as BoglanishRouteImport } from './routes/boglanish'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UstozRoute = UstozRouteImport.update({
  id: '/ustoz',
  path: '/ustoz',
  getParentRoute: () => rootRouteImport,
} as any)
const NatijalarRoute = NatijalarRouteImport.update({
  id: '/natijalar',
  path: '/natijalar',
  getParentRoute: () => rootRouteImport,
} as any)
const KurslarRoute = KurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigratsiyaRoute = ImmigratsiyaRouteImport.update({
  id: '/immigratsiya',
  path: '/immigratsiya',
  getParentRoute: () => rootRouteImport,
} as any)
const GalereyaRoute = GalereyaRouteImport.update({
  id: '/galereya',
  path: '/galereya',
  getParentRoute: () => rootRouteImport,
} as any)
const BoglanishRoute = BoglanishRouteImport.update({
  id: '/boglanish',
  path: '/boglanish',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boglanish': typeof BoglanishRoute
  '/galereya': typeof GalereyaRoute
  '/immigratsiya': typeof ImmigratsiyaRoute
  '/kurslar': typeof KurslarRoute
  '/natijalar': typeof NatijalarRoute
  '/ustoz': typeof UstozRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boglanish': typeof BoglanishRoute
  '/galereya': typeof GalereyaRoute
  '/immigratsiya': typeof ImmigratsiyaRoute
  '/kurslar': typeof KurslarRoute
  '/natijalar': typeof NatijalarRoute
  '/ustoz': typeof UstozRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/boglanish': typeof BoglanishRoute
  '/galereya': typeof GalereyaRoute
  '/immigratsiya': typeof ImmigratsiyaRoute
  '/kurslar': typeof KurslarRoute
  '/natijalar': typeof NatijalarRoute
  '/ustoz': typeof UstozRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boglanish'
    | '/galereya'
    | '/immigratsiya'
    | '/kurslar'
    | '/natijalar'
    | '/ustoz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/boglanish'
    | '/galereya'
    | '/immigratsiya'
    | '/kurslar'
    | '/natijalar'
    | '/ustoz'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boglanish'
    | '/galereya'
    | '/immigratsiya'
    | '/kurslar'
    | '/natijalar'
    | '/ustoz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoglanishRoute: typeof BoglanishRoute
  GalereyaRoute: typeof GalereyaRoute
  ImmigratsiyaRoute: typeof ImmigratsiyaRoute
  KurslarRoute: typeof KurslarRoute
  NatijalarRoute: typeof NatijalarRoute
  UstozRoute: typeof UstozRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ustoz': {
      id: '/ustoz'
      path: '/ustoz'
      fullPath: '/ustoz'
      preLoaderRoute: typeof UstozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natijalar': {
      id: '/natijalar'
      path: '/natijalar'
      fullPath: '/natijalar'
      preLoaderRoute: typeof NatijalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurslar': {
      id: '/kurslar'
      path: '/kurslar'
      fullPath: '/kurslar'
      preLoaderRoute: typeof KurslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigratsiya': {
      id: '/immigratsiya'
      path: '/immigratsiya'
      fullPath: '/immigratsiya'
      preLoaderRoute: typeof ImmigratsiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galereya': {
      id: '/galereya'
      path: '/galereya'
      fullPath: '/galereya'
      preLoaderRoute: typeof GalereyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boglanish': {
      id: '/boglanish'
      path: '/boglanish'
      fullPath: '/boglanish'
      preLoaderRoute: typeof BoglanishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoglanishRoute: BoglanishRoute,
  GalereyaRoute: GalereyaRoute,
  ImmigratsiyaRoute: ImmigratsiyaRoute,
  KurslarRoute: KurslarRoute,
  NatijalarRoute: NatijalarRoute,
  UstozRoute: UstozRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
