/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KurslarRouteImport } from './routes/kurslar'
import { Route as BoglanishRouteImport } from './routes/boglanish'
import { Route as IndexRouteImport } from './routes/index'

const KurslarRoute = KurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => rootRouteImport,
} as any)
const BoglanishRoute = BoglanishRouteImport.update({
  id: '/boglanish',
  path: '/boglanish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boglanish': typeof BoglanishRoute
  '/kurslar': typeof KurslarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boglanish': typeof BoglanishRoute
  '/kurslar': typeof KurslarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boglanish': typeof BoglanishRoute
  '/kurslar': typeof KurslarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boglanish' | '/kurslar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boglanish' | '/kurslar'
  id: '__root__' | '/' | '/boglanish' | '/kurslar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoglanishRoute: typeof BoglanishRoute
  KurslarRoute: typeof KurslarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kurslar': {
      id: '/kurslar'
      path: '/kurslar'
      fullPath: '/kurslar'
      preLoaderRoute: typeof KurslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boglanish': {
      id: '/boglanish'
      path: '/boglanish'
      fullPath: '/boglanish'
      preLoaderRoute: typeof BoglanishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoglanishRoute: BoglanishRoute,
  KurslarRoute: KurslarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
